### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by telegraphic** [FRBs/sigpyproc3#10]
It would be good to add a license! @ewanbarr and @pravirkr any opinion on this? I would suggest MIT/BSD license.

Related: https://github.com/telegraphic/numbits/issues/3

**Comment by pravirkr** [comment]
yeah, I think MIT is the simplest one.
@ewanbarr I could not find any license in the original repo. What do you suggest?

**Comment by pravirkr** [comment]
Ok, going ahead with the MIT license.
