### ISSUE TITLE
downsample is broken 

### ISSUE THREAD

**Issue by kmjc** [FRBs/sigpyproc3#19]
the call here
https://github.com/FRBs/sigpyproc3/blob/b1f87c0174ca5770d0e5b5380a53cdd2dd8b7a86/sigpyproc/base.py#L499-L501 
has an extra argument `write_arr` that isn't in the function
https://github.com/FRBs/sigpyproc3/blob/b1f87c0174ca5770d0e5b5380a53cdd2dd8b7a86/sigpyproc/core/kernels.py#L110

so doing something like
```
fil=FilReader(filfname)
myfil.downsample(tfactor=2)
```
gives 
```
downsample :  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:--
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sigpyproc3/sigpyproc/base.py", line 499, in downsample
    kernels.downsample_2d(
TypeError: too many arguments: expected 5, got 6
```

**Comment by pravirkr** [comment]
Thanks for reporting. a07d00c should fix this.
